# ===================================
#  List Behavior Config
# ===================================

#title: Title
modelClass: Wbry\Content\Models\Item
list: $/wbry/content/models/item/columns.yaml
recordUrl: 'wbry/content/items/:page_slug/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
  column: sort_order
  direction: asc
toolbar:
  buttons: list_toolbar
  search:
    prompt: 'backend::lang.list.search_prompt'