# ===================================
#  Form Behavior Config
# ===================================

name: "Content list"
modelClass: Wbry\Content\Models\Item
form: $/wbry/content/models/item/fields.yaml

create:
  redirect: wbry/content/items/:page/update/:id
  redirectClose: wbry/content/items/:page
update:
  redirectClose: wbry/content/items/:page
preview: {}