# ===================================
#  Form Behavior Config
# ===================================

name: "Content list"
modelClass: Wbry\Content\Models\Item
form: $/wbry/content/models/item/fields.yaml

create:
  redirect: wbry/content/items/:page_slug/update/:id
  redirectClose: wbry/content/items/:page_slug
update:
  redirectClose: wbry/content/items/:page_slug
delete:
  redirectClose: wbry/content/items/:page_slug
preview: {}