plugin:
    name: 'wbry.content::lang.plugin.name'
    description: 'wbry.content::lang.plugin.description'
    author: 'Weberry, Diamond'
    icon: oc-icon-list-alt
    homepage: ''
navigation:
    items:
        label: Content
        url: wbry/content/items
        icon: icon-list-alt
        permissions:
            - wbry.content.items
        sideMenu: {}
permissions:
    wbry.content.items:
        tab: 'wbry.content::lang.plugin.name'
        label: 'Управления контентом'
