plugin:
    name: 'wbry.content::lang.plugin.name'
    description: 'wbry.content::lang.plugin.description'
    author: Weberry
    icon: oc-icon-list-alt
    homepage: ''
navigation:
    items:
        label: Content
        url: wbry/content/items
        icon: icon-list-alt
        permissions:
            - wbry.content.items
        sideMenu:
            item-index:
                label: Главная
                url: wbry/content/items/index
                icon: icon-home
            item-products:
                label: Продукты
                url: wbry/content/items/products
                icon: icon-cubes
permissions:
    wbry.content.items:
        tab: 'wbry.content::lang.plugin.name'
        label: 'Управления контентом'
